using System;

namespace AGS.API
{
	public enum HatchStyle
	{
		BackwardDiagonal = 3,
		Cross,
		DarkDownwardDiagonal = 20,
		DarkHorizontal = 29,
		DarkUpwardDiagonal = 21,
		DarkVertical = 28,
		DashedDownwardDiagonal = 30,
		DashedHorizontal = 32,
		DashedUpwardDiagonal = 31,
		DashedVertical = 33,
		DiagonalBrick = 38,
		DiagonalCross = 5,
		Divot = 42,
		DottedDiamond = 44,
		DottedGrid = 43,
		ForwardDiagonal = 2,
		Horizontal = 0,
		HorizontalBrick = 39,
		LargeCheckerBoard = 50,
		LargeConfetti = 35,
		LargeGrid = 4,
		LightDownwardDiagonal = 18,
		LightHorizontal = 25,
		LightUpwardDiagonal = 19,
		LightVertical = 24,
		Max = 4,
		Min = 0,
		NarrowHorizontal = 27,
		NarrowVertical = 26,
		OutlinedDiamond = 51,
		Percent05 = 6,
		Percent10,
		Percent20,
		Percent25,
		Percent30,
		Percent40,
		Percent50,
		Percent60,
		Percent70,
		Percent75,
		Percent80,
		Percent90,
		Plaid = 41,
		Shingle = 45,
		SmallCheckerBoard = 49,
		SmallConfetti = 34,
		SmallGrid = 48,
		SolidDiamond = 52,
		Sphere = 47,
		Trellis = 46,
		Vertical = 1,
		Wave = 37,
		Weave = 40,
		WideDownwardDiagonal = 22,
		WideUpwardDiagonal,
		ZigZag = 36
	}
}

